trigger:
- master

pool:
  name: 'webgoat-agent'

variables:
 subscription: "Free Trial(02dd8a70-8b78-44e2-bb9e-56d6e1188f39)"
 appName:       "webgoattest"

stages:
- stage: Build
  jobs:
  - job: Buildjob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: CopyFiles@2
      inputs:
        Contents: '**/target/*.?(jar|war)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'groot-artifact'
        publishLocation: 'Container'



  
 
  - job: Deploymentjob
    dependsOn: Buildjob
    steps:
      
      - task: DownloadPipelineArtifact@2
        displayName: "Download Build Artifacts"
        inputs:
          buildType: 'current'
          artifactName: 'groot-artifact'
          path: '$(Pipeline.Workspace)/groot_artifact'


      - task: AzureWebApp@1
        inputs:
          azureSubscription: $(subscription)
          appType:           'webApp'
          appName:            $(appName)
          package:            '$(Build.ArtifactStagingDirectory)/*.?(jar|war)'  
